If there are formatting errors, upload a Git patch as artifact containing all necessary changes.

diff --git a/.github/workflows/clang_format.yml b/.github/workflows/clang_format.yml
--- a/.github/workflows/clang_format.yml
+++ b/.github/workflows/clang_format.yml
@@ -25,8 +25,25 @@ jobs:
         run: |
           cd PLSSVM
           cmake --preset all -DPLSSVM_TARGET_PLATFORMS=cpu -DPLSSVM_ENABLE_FORMATTING=ON
-      # build project
-      - name: Generate
+      # check formatting
+      - name: Check Formatting
         run: |
+          set +e
           cd PLSSVM
           cmake --build --preset all --target check-clang-format
+          status=$?
+          if [ $status -ne 0 ]; then
+            echo "Formatting errors found!"
+            cmake --build --preset all --target clang-format > clang-format-patch.txt 2>&1
+            exit $status
+          else
+            echo "No formatting errors found!"
+          fi
+      # upload the git patch, if available
+      - name: Upload Patch
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: clang-format-patch
+          path: PLSSVM/clang-format-patch.txt
+          if-no-files-found: ignore
